service: cloud-koala

frameworkVersion: "<2.0.0"

plugins:
  - serverless-python-requirements

provider:
  name: aws
  runtime: python2.7
  region: ap-southeast-2
  memorySize: 512
  timeout: 60
  stage: dev

custom:
  pythonRequirements:
    dockerizePip: true

functions:
  get_models:
    handler: handler.get_models
    events:
      - http:
          path: models
          method: get
          cors: true
  add_model:
    handler: handler.add_model
    events:
      - http:
          path: models
          method: post
          cors: true
  get_model:
    handler: handler.get_model
    events:
      - http:
          path: models/{model_id}
          method: get
          cors: true
  run_model:
    handler: handler.run_model
    events:
      - http:
          path: models/{model_id}
          method: post
          cors: true
  update_model:
    handler: handler.update_model
    events:
      - http:
          path: models/{model_id}
          method: post
          cors: true
  delete_model:
    handler: handler.delete_model
    events:
      - http:
          path: models/{model_id}
          method: delete
          cors: true

package:
    exclude:
        - env/**
        - tests/**
